// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/urijs.js";
import { group } from "k6";
import { htmlReport } from "https://raw.githubusercontent.com/benc-uk/k6-reporter/main/dist/bundle.js";


export let options = {
  maxRedirects: 4,
  thresholds: {
    http_req_duration: ['avg<500'],
  },
};

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  collection: {
    baseUrl: "http://10.10.30.19"
  }
});

export function handleSummary(data) {
  return {
    "summary.html": htmlReport(data),
  };
}

export default function() {
  group("auth", function() {
    postman[Request]({
      name: "App Controller login",
      id: "cd8d5b05-c644-4ea8-a563-6af6b2778237",
      method: "POST",
      address: "{{baseUrl}}/auth/login",
      data: '{\n  "username": "user01",\n  "password": "asdf"\n}',
      headers: {
        "Content-Type": "application/json"
      }
    });

    postman[Request]({
      name: "App Controller register",
      id: "3299a717-145b-401f-8693-bae15d67b10f",
      method: "POST",
      address: "{{baseUrl}}/auth/register",
      data:
        '{\n  "username": "user01",\n  "password": "asdf",\n  "profilePicture": "image/png;base64;alkdjfalk..."\n}',
      headers: {
        "Content-Type": "application/json"
      }
    });

    postman[Request]({
      name: "App Controller delete User",
      id: "0dc65fec-683e-45a6-930e-fb201a7b5f3f",
      method: "POST",
      address: "{{baseUrl}}/auth/delete",
      data: '{\n  "username": "user01"\n}',
      headers: {
        "Content-Type": "application/json"
      }
    });
  });

  group("user", function() {
    group("profile Pic", function() {
      postman[Request]({
        name: "App Controller change Profile Picture",
        id: "4882c2c4-34cd-4892-a33b-17296718e3cb",
        method: "POST",
        address: "{{baseUrl}}/user/profilePic",
        data: '{\n  "picture": "image/png;base64;alkdjfalk..."\n}',
        headers: {
          "Content-Type": "application/json"
        }
      });

      postman[Request]({
        name: "App Controller get Profile Picture",
        id: "3c93292e-1271-4726-8fa9-166e2515bd3a",
        method: "GET",
        address: "{{baseUrl}}/user/profilePic"
      });
    });

    postman[Request]({
      name: "App Controller get All User",
      id: "67155c64-e31a-4ff9-8c8b-506e6b51539b",
      method: "GET",
      address: "{{baseUrl}}/user/all",
      headers: {
        Accept: "application/json"
      }
    });

    postman[Request]({
      name: "App Controller is Valid",
      id: "e294e3c8-4d62-4127-8717-a804cee0af3b",
      method: "GET",
      address: "{{baseUrl}}/user/valid"
    });
  });

  group("pages", function() {
    postman[Request]({
      name: "Pages Controller create Page",
      id: "f923e212-050b-4562-b94f-a8fc77bc9405",
      method: "POST",
      address: "{{baseUrl}}/pages",
      data:
        '{\n  "projectId": "923u54on",\n  "name": "sn_labor",\n  "displayName": "Sn Labor",\n  "mapX": 50,\n  "mapY": 30\n}',
      headers: {
        "Content-Type": "application/json"
      }
    });

    postman[Request]({
      name: "Pages Controller get All Pages",
      id: "695bd07f-eb9b-46d3-862b-f74d83e5463a",
      method: "GET",
      address: "{{baseUrl}}/pages/all",
      headers: {
        Accept: "application/json"
      }
    });

    postman[Request]({
      name: "Pages Controller delete Page",
      id: "8bade226-0a04-4280-8553-b33811ffc533",
      method: "DELETE",
      address: "{{baseUrl}}/pages/ad qui laborum"
    });

    postman[Request]({
      name: "Pages Controller get All Pages For Project",
      id: "ebcd20f8-862f-40cf-8909-00e375eac4a7",
      method: "GET",
      address: "{{baseUrl}}/pages/:projectId",
      headers: {
        Accept: "application/json"
      }
    });
  });

  group("resources", function() {
    group("{resource Id}", function() {
      postman[Request]({
        name: "Resources Controller delete Resource",
        id: "2e23dff6-2542-4523-b5a0-f0f41b339640",
        method: "DELETE",
        address: "{{baseUrl}}/resources/ad qui laborum"
      });

      postman[Request]({
        name: "Resources Controller get Resource By Id",
        id: "4fd26a5f-2b1f-492a-91f0-522a9be6ab6f",
        method: "GET",
        address: "{{baseUrl}}/resources/ad qui laborum",
        headers: {
          Accept: "application/json"
        }
      });
    });

    postman[Request]({
      name: "Resources Controller add Resource",
      id: "e351c49c-f1d0-47ef-91d0-da5dac567183",
      method: "POST",
      address: "{{baseUrl}}/resources",
      data:
        '{\n  "type": "Text",\n  "blob": "image/png;base64;alkdjfalk...",\n  "style": {}\n}',
      headers: {
        "Content-Type": "application/json"
      }
    });

    postman[Request]({
      name: "Resources Controller get All Resources",
      id: "2c2ca4aa-f018-4b20-8c70-ea8fddaa42b2",
      method: "GET",
      address: "{{baseUrl}}/resources/all",
      headers: {
        Accept: "application/json"
      }
    });
  });

  group("container", function() {
    postman[Request]({
      name: "Container Controller create Container",
      id: "90ab9b06-6191-4726-ab0d-b86395aefb09",
      method: "POST",
      address: "{{baseUrl}}/container",
      data:
        '{\n  "pageId": "ajsknkfd7sdf",\n  "name": "logo_1",\n  "xCoordinate": 39,\n  "yCoordinate": 29,\n  "width": 29,\n  "height": 29,\n  "resourceId": "aisjdf8sud"\n}',
      headers: {
        "Content-Type": "application/json"
      }
    });

    postman[Request]({
      name: "Container Controller delete Container",
      id: "66c09d20-2c1e-4b64-b638-77423c7710c4",
      method: "DELETE",
      address: "{{baseUrl}}/container/ad qui laborum"
    });

    postman[Request]({
      name: "Container Controller get All Container",
      id: "3de8a1fa-c308-40e3-88ab-efefaad29486",
      method: "GET",
      address: "{{baseUrl}}/container/all",
      headers: {
        Accept: "application/json"
      }
    });

    postman[Request]({
      name: "Container Controller get All Container For Page Id",
      id: "42e5fdae-3728-4560-a642-bdcd21877cf8",
      method: "GET",
      address: "{{baseUrl}}/container/ad qui laborum",
      headers: {
        Accept: "application/json"
      }
    });
  });

  group("projects", function() {
    postman[Request]({
      name: "Projects Controller get All",
      id: "46556ec2-2806-4025-855d-e06a896141cf",
      method: "GET",
      address: "{{baseUrl}}/projects",
      headers: {
        Accept: "application/json"
      }
    });

    postman[Request]({
      name: "Projects Controller create",
      id: "047ee63e-3fe2-4eb9-ab55-a4dc3c885276",
      method: "POST",
      address: "{{baseUrl}}/projects",
      data:
        '{\n  "projectName": "TFO tour",\n  "description": "Cool tfo tour",\n  "mapBlob": "image/png;base64;alkdjfalk..."\n}',
      headers: {
        "Content-Type": "application/json"
      }
    });

    postman[Request]({
      name: "Projects Controller delete",
      id: "b879447a-adaa-480c-ba24-76fde814588e",
      method: "DELETE",
      address: "{{baseUrl}}/projects/ad qui laborum"
    });
  });

  postman[Request]({
    name: "App Controller test",
    id: "4bf48302-ae72-448a-b82e-f3d646afff19",
    method: "GET",
    address: "{{baseUrl}}/",
    headers: {
      Accept: "application/json"
    }
  });

  postman[Request]({
    name: "Prometheus Controller index",
    id: "73fdb409-83db-4510-bcdf-a6b24b7c50ea",
    method: "GET",
    address: "{{baseUrl}}/metrics"
  });
}
